# Generated by Django 4.2.1 on 2023-06-04 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="devices",
        ),
        migrations.AlterField(
            model_name="devicecheck",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_checks",
                to="assets.device",
            ),
        ),
        migrations.AlterField(
            model_name="devicecheck",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_checks",
                to="assets.employee",
            ),
        ),
    ]
