# Generated by Django 4.2.1 on 2023-06-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicecheck",
            name="condition_in",
            field=models.CharField(
                choices=[("Good", "Good"), ("Fair", "Fair"), ("Poor", "Poor")],
                default="Good",
                max_length=10,
            ),
        ),
    ]
